name: Build Morning Briefing (manual + daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 12 * * *"  # 12:10 UTC = 6:10 AM CST / 7:10 AM CDT

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: keep this for a few runs, then remove
      - name: Show workspace tree
        run: |
          echo "PWD = $(pwd)"
          ls -la
          ls -la .github || true
          ls -la .github/scripts || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ".github/scripts/requirements.txt"

      - name: Install deps
        run: pip install -r .github/scripts/requirements.txt

      - name: Run builder
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
        run: python -u .github/scripts/build_playlist.py
