jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "PWD = $(pwd)"
          echo "Tree (root):"
          ls -la
          echo "Tree .github:"
          ls -la .github || true
          echo "Tree .github/scripts:"
          ls -la .github/scripts || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ".github/scripts/requirements.txt"

      - name: Install deps
        run: pip install -r .github/scripts/requirements.txt

      - name: Show first lines of script
        run: sed -n '1,140p' .github/scripts/build_playlist.py

      - name: Echo env names (not values)
        run: |
          env | grep -E '^SPOTIFY_(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|PLAYLIST_ID)=' \
          | sed 's/=.*/=<hidden>/' || true

      - name: Run builder (unbuffered)
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
        run: python -u .github/scripts/build_playlist.py
